export const FETCH_EXPERIENCES_START = 'FETCH_EXPERIENCES_START';
export const FETCH_EXPERIENCES_SUCCESS = 'FETCH_EXPERIENCES_SUCCESS';
export const FETCH_EXPERIENCES_FAILURE = 'FETCH_EXPERIENCES_FAILURE';

export const FETCH_EXPERIENCE_BY_ID_START = 'FETCH_EXPERIENCE_BY_ID_START';
export const FETCH_EXPERIENCE_BY_ID_SUCCESS = 'FETCH_EXPERIENCE_BY_ID_SUCCESS';
export const FETCH_EXPERIENCE_BY_ID_FAILURE = 'FETCH_EXPERIENCE_BY_ID_FAILURE';

export const CREATE_EXPERIENCE_START = 'CREATE_EXPERIENCE_START';
export const CREATE_EXPERIENCE_SUCCESS = 'CREATE_EXPERIENCE_SUCCESS';
export const CREATE_EXPERIENCE_FAILURE = 'CREATE_EXPERIENCE_FAILURE';
