export const FETCH_EXPERIENCES_START = 'FETCH_EXPERIENCES_START';
export const FETCH_EXPERIENCES_SUCCESS = 'FETCH_EXPERIENCES_SUCCESS';
export const FETCH_EXPERIENCES_FAILURE = 'FETCH_EXPERIENCES_FAILURE';

export const FETCH_EXPERIENCE_BY_ID_START = 'FETCH_EXPERIENCE_BY_ID_START';
export const FETCH_EXPERIENCE_BY_ID_SUCCESS = 'FETCH_EXPERIENCE_BY_ID_SUCCESS';
export const FETCH_EXPERIENCE_BY_ID_FAILURE = 'FETCH_EXPERIENCE_BY_ID_FAILURE';

export const CREATE_EXPERIENCE_START = 'CREATE_EXPERIENCE_START';
export const CREATE_EXPERIENCE_SUCCESS = 'CREATE_EXPERIENCE_SUCCESS';
export const CREATE_EXPERIENCE_FAILURE = 'CREATE_EXPERIENCE_FAILURE';

export const EDIT_EXPERIENCE_START = 'EDIT_EXPERIENCE_START';
export const EDIT_EXPERIENCE_SUCCESS = 'EDIT_EXPERIENCE_SUCCESS';
export const EDIT_EXPERIENCE_FAILURE = 'EDIT_EXPERIENCE_FAILURE';

export const DELETE_EXPERIENCE_START = 'DELETE_EXPERIENCE_START';
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const DELETE_EXPERIENCE_FAILURE = 'DELETE_EXPERIENCE_FAILURE';

export const UPLOAD_EXPERIENCE_START = 'DELETE_EXPERIENCE_START';
export const UPLOAD_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS';
export const UPLOAD_EXPERIENCE_FAILURE = 'DELETE_EXPERIENCE_FAILURE';
