export const FETCH_YACHTS_START = 'FETCH_YACHTS_START';
export const FETCH_YACHTS_SUCCESS = 'FETCH_YACHTS_SUCCESS';
export const FETCH_YACHTS_FAILURE = 'FETCH_YACHTS_FAILURE';

export const FETCH_YACHT_BY_ID_START = 'FETCH_YACHT_BY_ID_START';
export const FETCH_YACHT_BY_ID_SUCCESS = 'FETCH_YACHT_BY_ID_SUCCESS';
export const FETCH_YACHT_BY_ID_FAILURE = 'FETCH_YACHT_BY_ID_FAILURE';
