export const FETCH_YACHTS_START = 'FETCH_YACHTS_START';
export const FETCH_YACHTS_SUCCESS = 'FETCH_YACHTS_SUCCESS';
export const FETCH_YACHTS_FAILURE = 'FETCH_YACHTS_FAILURE';

export const FETCH_ADMIN_YACHTS_START = 'FETCH_ADMIN_YACHTS_START';
export const FETCH_ADMIN_YACHTS_SUCCESS = 'FETCH_ADMIN_YACHTS_SUCCESS';
export const FETCH_ADMIN_YACHTS_FAILURE = 'FETCH_ADMIN_YACHTS_FAILURE';

export const FILTER_YACHTS_START = 'FILTER_YACHTS_START';
export const FILTER_YACHTS_SUCCESS = 'FILTER_YACHTS_SUCCESS';
export const FILTER_YACHTS_FAIL = 'FILTER_YACHTS_FAIL';

export const FETCH_YACHT_BY_ID_START = 'FETCH_YACHT_BY_ID_START';
export const FETCH_YACHT_BY_ID_SUCCESS = 'FETCH_YACHT_BY_ID_SUCCESS';
export const FETCH_YACHT_BY_ID_FAILURE = 'FETCH_YACHT_BY_ID_FAILURE';

export const CREATE_YACHT_START = 'CREATE_YACHT_START';
export const CREATE_YACHT_SUCCESS = 'CREATE_YACHT_SUCCESS';
export const CREATE_YACHT_FAILURE = 'CREATE_YACHT_FAILURE';

export const EDIT_YACHT_START = 'EDIT_YACHT_START';
export const EDIT_YACHT_SUCCESS = 'EDIT_YACHT_SUCCESS';
export const EDIT_YACHT_FAILURE = 'EDIT_YACHT_FAILURE';

export const FETCH_FLAG_START = 'FETCH_FLAG_START';
export const FETCH_FLAG_SUCCESS = 'FETCH_FLAG_SUCCESS';
export const FETCH_FLAG_FAILURE = 'FETCH_FLAG_FAILURE';

export const FETCH_COUNTRY_START = 'FETCH_COUNTRY_START';
export const FETCH_COUNTRY_SUCCESS = 'FETCH_COUNTRY_SUCCESS';
export const FETCH_COUNTRY_FAILURE = 'FETCH_COUNTRY_FAILURE';

export const FETCH_HOMEPORT_START = 'FETCH_HOMEPORT_START';
export const FETCH_HOMEPORT_SUCCESS = 'FETCH_HOMEPORT_SUCCESS';
export const FETCH_HOMEPORT_FAILURE = 'FETCH_HOMEPORT_FAILURE';

export const FETCH_WATERTOYS_START = 'FETCH_WATERTOYS_START';
export const FETCH_WATERTOYS_SUCCESS = 'FETCH_WATERTOYS_SUCCESS';
export const FETCH_WATERTOYS_FAILURE = 'FETCH_WATERTOYS_FAILURE';

export const FETCH_INCLUSIVETERM_START = 'FETCH_INCLUSIVETERM_START';
export const FETCH_INCLUSIVETERM_SUCCESS = 'FETCH_INCLUSIVETERM_SUCCESS';
export const FETCH_INCLUSIVETERM_FAILURE = 'FETCH_INCLUSIVETERM_FAILURE';

export const FETCH_EXTRAS_START = 'FETCH_EXTRAS_START';
export const FETCH_EXTRAS_SUCCESS = 'FETCH_EXTRAS_SUCCESS';
export const FETCH_EXTRAS_FAILURE = 'FETCH_EXTRAS_FAILURE';

export const FETCH_YACHT_FEATURES_START = 'FETCH_YACHT_FEATURES_START';
export const FETCH_YACHT_FEATURES_FAILURE = 'FETCH_YACHT_FEATURES_FAILURE';
export const FETCH_YACHT_FEATURES_SUCCESS = 'FETCH_YACHT_FEATURES_SUCCESS';
//////////////////////////////////////////////////////////
export const ADD_PIC_START = 'ADD_PIC_START';
export const ADD_PIC_SUCCESS = 'ADD_PIC_SUCCESS';
export const ADD_PIC_STOP = 'ADD_PIC_STOP';
