export const FETCH_YACHTS_START = 'FETCH_YACHTS_START';
export const FETCH_YACHTS_SUCCESS = 'FETCH_YACHTS_SUCCESS';
export const FETCH_YACHTS_FAILURE = 'FETCH_YACHTS_FAILURE';

export const FETCH_ADMIN_YACHTS_START = 'FETCH_ADMIN_YACHTS_START';
export const FETCH_ADMIN_YACHTS_SUCCESS = 'FETCH_ADMIN_YACHTS_SUCCESS';
export const FETCH_ADMIN_YACHTS_FAILURE = 'FETCH_ADMIN_YACHTS_FAILURE';

export const FETCH_YACHT_BY_ID_START = 'FETCH_YACHT_BY_ID_START';
export const FETCH_YACHT_BY_ID_SUCCESS = 'FETCH_YACHT_BY_ID_SUCCESS';
export const FETCH_YACHT_BY_ID_FAILURE = 'FETCH_YACHT_BY_ID_FAILURE';

export const CREATE_YACHT_START = 'CREATE_YACHT_START';
export const CREATE_YACHT_SUCCESS = 'CREATE_YACHT_SUCCESS';
export const CREATE_YACHT_FAILURE = 'CREATE_YACHT_FAILURE';

export const EDIT_YACHT_START = 'EDIT_YACHT_START';
export const EDIT_YACHT_SUCCESS = 'EDIT_YACHT_SUCCESS';
export const EDIT_YACHT_FAILURE = 'EDIT_YACHT_FAILURE';
