export const FETCH_DESTINATION_START = 'FETCH_DESTINATION_START';
export const FETCH_DESTINATION_SUCCESS = 'FETCH_DESTINATION_SUCCESS';
export const FETCH_DESTINATION_FAILURE = 'FETCH_DESTINATION_FAILURE';
