export const FETCH_DESTINATION_START = 'FETCH_DESTINATION_START';
export const FETCH_DESTINATION_SUCCESS = 'FETCH_DESTINATION_SUCCESS';
export const FETCH_DESTINATION_FAILURE = 'FETCH_DESTINATION_FAILURE';

export const CREATE_DESTINATION_START = 'CREATE_DESTINATION_START';
export const CREATE_DESTINATION_SUCCESS = 'CREATE_DESTINATION_SUCCESS';
export const CREATE_DESTINATION_FAIL = 'CREATE_DESTINATION_FAIL';

export const DELETE_DESTINATION_START = 'DELETE_DESTINATION_START';
export const DELETE_DESTINATION_SUCCESS = 'DELETE_DESTINATION_SUCCESS';
export const DELETE_DESTINATION_FAIL = 'DELETE_DESTINATION_FAIL';

export const FETCH_RANDOM_DESTINATION_START = 'FETCH_RANDOM_DESTINATION_START';
export const FETCH_RANDOM_DESTINATION_SUCCESS =
  'FETCH_RANDOM_DESTINATION_SUCCESS';
export const FETCH_RANDOM_DESTINATION_FAILURE =
  'FETCH_RANDOM_DESTINATION_FAILURE';

export const FETCH_DESTINATION_BY_ID_START = 'FETCH_DESTINATION_BY_ID_START';
export const FETCH_DESTINATION_BY_ID_SUCCESS =
  'FETCH_DESTINATION_BY_ID_SUCCESS';
export const FETCH_DESTINATION_BY_ID_FAILURE =
  'FETCH_DESTINATION_BY_ID_FAILURE';
