export const FETCH_DESTINATION_START = 'FETCH_DESTINATION_START';
export const FETCH_DESTINATION_SUCCESS = 'FETCH_DESTINATION_SUCCESS';
export const FETCH_DESTINATION_FAILURE = 'FETCH_DESTINATION_FAILURE';

export const FETCH_RANDOM_DESTINATION_START = 'FETCH_RANDOM_DESTINATION_START';
export const FETCH_RANDOM_DESTINATION_SUCCESS =
  'FETCH_RANDOM_DESTINATION_SUCCESS';
export const FETCH_RANDOM_DESTINATION_FAILURE =
  'FETCH_RANDOM_DESTINATION_FAILURE';
