export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
////////////////////////////////////////////////////////////
export const FETCH_RANDOM_POSTS_START = 'FETCH_RANDOM_POSTS_START';
export const FETCH_RANDOM_POSTS_SUCCESS = 'FETCH_RANDOM_POSTS_SUCCESS';
export const FETCH_RANDOM_POSTS_FAILURE = 'FETCH_RANDOM_POSTS_FAILURE';
/////////////////////////////////////////////////////////////
export const FETCH_POSTS_BY_ID_START = 'FETCH_POSTS_BY_ID_START';
export const FETCH_POSTS_BY_ID_SUCCESS = 'FETCH_POSTS_BY_ID_SUCCESS';
export const FETCH_POSTS_BY_ID_FAILURE = 'FETCH_POSTS_BY_ID_FAILURE';

export const CREATE_POST_START = 'CREATE_POST_START';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE';
