export const FETCH_OFFER_START = 'FETCH_OFFER_START';
export const FETCH_OFFER_SUCCESS = 'FETCH_OFFER_SUCCESS';
export const FETCH_OFFER_FAILURE = 'FETCH_OFFER_FAILURE';

export const CREATE_GENERIC_OFFER_START = 'CREATE_GENERIC_OFFER_START';
export const CREATE_GENERIC_OFFER_SUCCESS = 'CREATE_GENERIC_OFFER_SUCCESS';
export const CREATE_GENERIC_OFFER_FAILURE = 'CREATE_GENERIC_OFFER_FAILURE';

export const FETCH_GENERIC_OFFER_BY_ID_START =
  'FETCH_GENERIC_OFFER_BY_ID_START';
export const FETCH_GENERIC_OFFER_BY_ID_SUCCESS =
  'FETCH_GENERIC_OFFER_BY_ID_SUCCESS';
export const FETCH_GENERIC_OFFER_BY_ID_FAILURE =
  'FETCH_GENERIC_OFFER_BY_ID_FAILURE';

export const DELETE_GENERIC_OFFER_START = 'DELETE_GENERIC_OFFER_START';
export const DELETE_GENERIC_OFFER_SUCCESS = 'DELETE_GENERIC_OFFER_SUCCESS';
export const DELETE_GENERIC_OFFER_FAILURE = 'DELETE_GENERIC_OFFER_FAILURE';

export const EDIT_GENERIC_OFFER_START = 'EDIT_GENERIC_OFFER_START';
export const EDIT_GENERIC_OFFER_SUCCESS = 'EDIT_GENERIC_OFFER_SUCCESS';
export const EDIT_GENERIC_OFFER_FAILURE = 'EDIT_GENERIC_OFFER_FAILURE';
